version: '3.9'
services:
   openzipkin-zipkin:
      image: openzipkin/zipkin:latest
      container_name: openzipkin-zipkin
      restart: always
      ports:
      - '9411:9411'
      networks:
      - microservices
   apache-activemq:
      image: lsefiane/activemq:5.16.2-alpine
      container_name: apache-activemq
      restart: always
      build:
         context: .
         dockerfile: docker/apache-activemq/5.16.2-alpine/Dockerfile
      ports:
      - '8161:8161'
      - '61616:61616'
      networks:
      - microservices
   hashicorp-consul:
      image: consul:latest
      container_name: hashicorp-consul
      command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
      restart: always
      ports:
      - '8500:8500'
      networks:
      - microservices
      environment:
      - CONSUL_BIND_INTERFACE=eth0
   gateway-service:
      image: lsefiane/gateway-service:latest
      container_name: gateway-service
      restart: always
      build:
         context: .
         dockerfile: docker/gateway-service/Dockerfile
      ports:
      - '8080:8080'
      depends_on:
      - hashicorp-consul
      volumes:
         - gateway-service-vol:/gateway-service
      networks:
      - microservices
      environment:
      - SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED}
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED}
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - SPRING_ZIPKIN_ENABLED=${SPRING_ZIPKIN_ENABLED}
      - SPRING_ZIPKIN_BASE_URL=${SPRING_ZIPKIN_BASE_URL}      
   publisher-service:
      image: lsefiane/publisher-service:latest
      container_name: publisher-service
      restart: always
      build:
         context: .
         dockerfile: docker/publisher-service/Dockerfile
      volumes:
         -  publisher-service-vol:/publisher-service
      depends_on:
      - apache-activemq
      - hashicorp-consul
      environment:
      - SPRING_ACTIVEMQ_BROKER_URL=${SPRING_ACTIVEMQ_BROKER_URL}
      - SPRING_ACTIVEMQ_USER=${SPRING_ACTIVEMQ_USER}
      - SPRING_ACTIVEMQ_PASSWORD=${SPRING_ACTIVEMQ_PASSWORD}
      - SPRING_JMS_LISTENER_AUTO_STARTUP=${SPRING_JMS_LISTENER_AUTO_STARTUP}   
      - SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED}
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - SPRING_ZIPKIN_ENABLED=${SPRING_ZIPKIN_ENABLED}
      - SPRING_ZIPKIN_BASE_URL=${SPRING_ZIPKIN_BASE_URL}
      networks:
      - microservices
   subscriber-service:
      image: lsefiane/subscriber-service:latest
      container_name: subscriber-service
      restart: always
      build:
         context: .
         dockerfile: docker/subscriber-service/Dockerfile
      volumes:
         - subscriber-service-vol:/subscriber-service
      depends_on:
      - apache-activemq
      - hashicorp-consul
      environment:
      - SPRING_ACTIVEMQ_BROKER_URL=${SPRING_ACTIVEMQ_BROKER_URL}
      - SPRING_ACTIVEMQ_USER=${SPRING_ACTIVEMQ_USER}
      - SPRING_ACTIVEMQ_PASSWORD=${SPRING_ACTIVEMQ_PASSWORD}
      - SPRING_JMS_LISTENER_AUTO_STARTUP=${SPRING_JMS_LISTENER_AUTO_STARTUP}     
      - SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED} 
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_ZIPKIN_ENABLED=${SPRING_ZIPKIN_ENABLED}
      - SPRING_ZIPKIN_BASE_URL=${SPRING_ZIPKIN_BASE_URL}
      networks:
      - microservices

volumes:
   publisher-service-vol:
   subscriber-service-vol:
   gateway-service-vol:

networks:
   microservices:
   