version: '3'
services:
   apache-activemq:
      image: lsefiane/activemq:latest
      container_name: apache-activemq
      restart: always
      build:
         context: .
         dockerfile: ./docker/apache-activemq/5.16.2/Dockerfile
      ports:
      - '8161:8161'
      - '61616:61616'
      depends_on:
      - publisher-service
      - subscriber-service
      networks:
      - microservices
   gateway-service:
      image: lsefiane/gateway-service:latest
      container_name: gateway-service
      restart: always
      build:
         context: .
         dockerfile: ./docker/gateway-service/Dockerfile
      ports:
      - '8080:8080'
      networks:
      - microservices
   publisher-service:
      image: lsefiane/publisher-service:latest
      restart: always
      build:
         context: .
         dockerfile: ./docker/publisher-service/Dockerfile
      deploy:
         mode: replicated
         replicas: 1
      environment:
      - SPRING_ACTIVEMQ_BROKER_URL=${SPRING_ACTIVEMQ_BROKER_URL}
      - SPRING_ACTIVEMQ_USER=${SPRING_ACTIVEMQ_USER}
      - SPRING_ACTIVEMQ_PASSWORD=${SPRING_ACTIVEMQ_PASSWORD}
      - SPRING_JMS_LISTENER_AUTO_STARTUP=${SPRING_JMS_LISTENER_AUTO_STARTUP}   
      networks:
      - microservices
   subscriber-service:
      image: lsefiane/subscriber-service:latest
      restart: always
      build:
         context: .
         dockerfile: ./docker/subscriber-service/Dockerfile
      deploy:
         mode: replicated
         replicas: 3
      environment:
      - SPRING_ACTIVEMQ_BROKER_URL=${SPRING_ACTIVEMQ_BROKER_URL}
      - SPRING_ACTIVEMQ_USER=${SPRING_ACTIVEMQ_USER}
      - SPRING_ACTIVEMQ_PASSWORD=${SPRING_ACTIVEMQ_PASSWORD}  
      - SPRING_JMS_LISTENER_AUTO_STARTUP=${SPRING_JMS_LISTENER_AUTO_STARTUP}      
      networks:
      - microservices
networks:
   microservices:
      driver: bridge
   