apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: k8s-dev
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /publisher
            backend:
              serviceName: publisher-service
              servicePort: 8080