apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
  namespace: k8s
  labels:
    app: subscriber-service
spec:
  selector:
    app: subscriber-service
  ports:
    - name: "8080"
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-service
  namespace: k8s
  labels:
    app: subscriber-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscriber-service
  template:
    metadata:
      labels:
        app: subscriber-service
    spec:
      containers:
        - image: lsefiane/subscriber-service:latest
          name: publisher-service
          env:
            - name: SPRING_ACTIVEMQ_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: publisher-subscriber-config
                  key: SPRING_ACTIVEMQ_BROKER_URL

            - name: SPRING_ACTIVEMQ_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: SPRING_ACTIVEMQ_USER

            - name: SPRING_ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: SPRING_ACTIVEMQ_PASSWORD

            - name: SPRING_ZIPKIN_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: publisher-subscriber-config
                  key: SPRING_ZIPKIN_BASE_URL

            - name: SPRING_ZIPKIN_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: publisher-subscriber-config
                  key: SPRING_ZIPKIN_ENABLED